In [1]:
import numpy as np

In [104]:
li1 = [1.5, 2, 3]
li2 = [[1, 2, 3],
      [4, 5, 6]]
nd1 = np.array(li1)
nd2 = np.array(li2)

display(nd1)
display(nd2)

array([1.5, 2. , 3. ])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
nd3 = np.array(li2, order="F")
display(nd3)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(nd1.shape, nd2.shape, nd3.shape)

(3,) (2, 3) (2, 3)


In [14]:
display(nd2.ndim)
display(nd2.shape)
display(nd2.size)
display(nd2.itemsize)
display(nd2.dtype)

2

(2, 3)

6

4

dtype('int32')

In [150]:
print(nd1.ndim)
print(nd1.shape)
print(nd1.dtype)
print(nd1.size)
print(nd1.itemsize)
print(nd1.nbytes)

1
(3,)
float64
3
8
24


In [25]:
li3 = [1, 1.5, "hehe", True]
nd3 = np.array(li3)
nd3

array(['1', '1.5', 'hehe', 'True'], dtype='<U32')

In [27]:
nd3.shape = (2, 2)

In [28]:
nd3

array([['1', '1.5'],
       ['hehe', 'True']], dtype='<U32')

In [36]:
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
np.arange(10, 40, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [46]:
np.linspace(1, 99)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [49]:
np.logspace(1, 16, num=5, endpoint=False)

array([1.e+01, 1.e+04, 1.e+07, 1.e+10, 1.e+13])

In [54]:
nd5 = np.arange(1, 26).reshape((5, 5))
nd5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
display(np.diag(nd5))
display(np.diag(nd5, k=1))
display(np.diag(nd5, k=-1))

array([ 1,  7, 13, 19, 25])

array([ 2,  8, 14, 20])

array([ 6, 12, 18, 24])

In [59]:
np.diag([1, 2, 3, 4, 5], k=-1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

In [62]:
np.diag?

In [68]:
display(np.zeros((5, )))
display(np.zeros((5, 5)))
display(np.zeros((2, 3, 5)))

array([0., 0., 0., 0., 0.])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [70]:
np.zeros_like(nd2)

array([[0, 0, 0],
       [0, 0, 0]])

In [73]:
np.zeros(nd2.shape, dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [75]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [102]:
np.full(nd2.shape, "he")

array([['he', 'he', 'he'],
       ['he', 'he', 'he']], dtype='<U2')

In [108]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [110]:
np.eye(5, 6, k=1, dtype="int32")

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [106]:
np.full_like(nd2, 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [109]:
np.eye?

In [131]:
np.random.random(8).reshape((2, 4))

array([[0.06636575, 0.51732547, 0.26669155, 0.41111383],
       [0.34430679, 0.04251134, 0.61940273, 0.48127959]])

In [123]:
np.random.rand(3, 5)

array([[0.39099003, 0.85981402, 0.57035725, 0.24815976, 0.32190469],
       [0.65937606, 0.14979711, 0.5187385 , 0.1178939 , 0.53792383],
       [0.76395289, 0.0743027 , 0.35945436, 0.81728109, 0.54413333]])

In [125]:
np.random.randn(3, 5)

array([[ 0.06136656,  0.42359674, -0.54382094,  2.12903231, -0.49941362],
       [ 1.43646184,  0.37490108, -0.25632178,  1.99407274, -0.05576798],
       [-0.63540279,  0.33159704, -0.77540964, -0.52714672, -1.06219599]])

In [128]:
np.random.randint(1, 100, (2, 4))

array([[29, 13, 68, 55],
       [65, 49, 48,  8]])

In [133]:
np.random.seed(5)
np.random.random(10)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119,
       0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123])

In [197]:
a = np.random.random(10)
a

array([0.10198849, 0.34397154, 0.82000126, 0.92464576, 0.75815227,
       0.87908158, 0.85414501, 0.17044836, 0.58471732, 0.35069356])

In [198]:
np.random.shuffle(a)
a

array([0.34397154, 0.17044836, 0.82000126, 0.75815227, 0.87908158,
       0.85414501, 0.58471732, 0.10198849, 0.35069356, 0.92464576])

In [138]:
mytype = np.dtype([("name", np.str_, 40), ("num", np.int64), ("price", np.float64)])

print(mytype["name"])
print(np.dtype(mytype["num"]))

<U40
int64


In [140]:
item = np.array([("hehehe", 3, 4.14), ("lalala", 8, 1.72)], dtype=mytype)
display(item)
display(item.shape)

array([('hehehe', 3, 4.14), ('lalala', 8, 1.72)],
      dtype=[('name', '<U40'), ('num', '<i8'), ('price', '<f8')])

(2,)

In [151]:
item = np.array([["hehehe", 3, 4.14], ["lalala", 8, 1.72]])
item
np.random.shuffle?

#### Properties
* np.ndim
* np.shape
* np.size
* np.itemsize
* np.dtype
* np.nbytes

#### 1-dimension
* np.arange
* np.linspace
* np.logspace
* np.diag

#### Multi-dimension
* np.ones
* np.ones_like
* np.zeros
* np.zeros_like
* np.full
* np.full_like - can only use int or float in the fill_value parameter.
* np.identity
* np.eye

#### Random module
* np.random.random(size)
* np.random.rand(d0, d1, ...)
* np.random.randn(d0, d1, ...)
* np.random.randint(low, high, size)
* np.random.seed(seed)
* np.random.shuffle(array_like)

In [157]:
chessboard = np.zeros((8, 8), dtype=int)
chessboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [158]:
for i in range(8):
    for j in range(8):
        if (i % 2 == 0 and j % 2 != 0) or (i % 2 != 0 and j % 2 == 0):
            chessboard[i, j] = 1

In [160]:
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
a_chessboard = np.ones((8, 8), dtype=int)
a_chessboard[::2, ::2] = 0
a_chessboard[1::2, 1::2] = 0
a_chessboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [170]:
arr = np.random.randint(1, 100, (6, 5))
arr

array([[87, 73, 33, 16, 70],
       [36, 63, 44,  1,  3],
       [ 3, 92, 66, 46, 88],
       [ 2, 24, 51, 87, 20],
       [55, 25, 65, 78, 74],
       [ 2, 10, 65, 24, 40]])

In [173]:
display(arr[3, 4])
display(arr[3][4])
display(arr[[1, 3, 4]])
display(arr[[True, False, False, True, True, False]])

20

20

array([[36, 63, 44,  1,  3],
       [ 2, 24, 51, 87, 20],
       [55, 25, 65, 78, 74]])

array([[87, 73, 33, 16, 70],
       [ 2, 24, 51, 87, 20],
       [55, 25, 65, 78, 74]])

In [174]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [176]:
arr1[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [180]:
arr2 = np.random.randint(1, 100, (6, 5))
arr2

array([[82, 92, 37, 98, 88],
       [70, 37, 19, 35, 31],
       [78, 98, 36, 30,  2],
       [83, 21,  1, 35, 79],
       [52, 31, 41, 75, 70],
       [80, 54, 20, 47, 27]])

In [181]:
arr2[2:, :]

array([[78, 98, 36, 30,  2],
       [83, 21,  1, 35, 79],
       [52, 31, 41, 75, 70],
       [80, 54, 20, 47, 27]])

In [182]:
arr2[2:][:]

array([[78, 98, 36, 30,  2],
       [83, 21,  1, 35, 79],
       [52, 31, 41, 75, 70],
       [80, 54, 20, 47, 27]])

In [183]:
arr2[2:, 3]

array([30, 35, 75, 47])

In [185]:
arr2[2:, [0, 1, 3]]

array([[78, 98, 30],
       [83, 21, 35],
       [52, 31, 75],
       [80, 54, 47]])

In [193]:
arr2.resize((3, 10))

In [194]:
arr2

array([[82, 92, 37, 98, 88, 70, 37, 19, 35, 31],
       [78, 98, 36, 30,  2, 83, 21,  1, 35, 79],
       [52, 31, 41, 75, 70, 80, 54, 20, 47, 27]])

In [195]:
arr2.reshape((10, 3))

array([[82, 92, 37],
       [98, 88, 70],
       [37, 19, 35],
       [31, 78, 98],
       [36, 30,  2],
       [83, 21,  1],
       [35, 79, 52],
       [31, 41, 75],
       [70, 80, 54],
       [20, 47, 27]])

In [196]:
arr2

array([[82, 92, 37, 98, 88, 70, 37, 19, 35, 31],
       [78, 98, 36, 30,  2, 83, 21,  1, 35, 79],
       [52, 31, 41, 75, 70, 80, 54, 20, 47, 27]])

In [204]:
a = np.random.randint(1, 100, 30).reshape((5, 6))
a

array([[80, 18, 88, 12, 31, 27],
       [ 9, 52, 62, 85, 53, 75],
       [26, 10, 32, 40, 60, 23],
       [81, 59, 45, 16, 16, 96],
       [78, 82, 58, 47, 20, 46]])

In [206]:
b = a.ravel()
b

array([80, 18, 88, 12, 31, 27,  9, 52, 62, 85, 53, 75, 26, 10, 32, 40, 60,
       23, 81, 59, 45, 16, 16, 96, 78, 82, 58, 47, 20, 46])

In [207]:
b.resize((3, 10))

In [208]:
a

array([[80, 18, 88, 12, 31, 27],
       [ 9, 52, 62, 85, 53, 75],
       [26, 10, 32, 40, 60, 23],
       [81, 59, 45, 16, 16, 96],
       [78, 82, 58, 47, 20, 46]])

In [209]:
b

array([[80, 18, 88, 12, 31, 27,  9, 52, 62, 85],
       [53, 75, 26, 10, 32, 40, 60, 23, 81, 59],
       [45, 16, 16, 96, 78, 82, 58, 47, 20, 46]])

In [210]:
c = a.flatten()

In [211]:
c

array([80, 18, 88, 12, 31, 27,  9, 52, 62, 85, 53, 75, 26, 10, 32, 40, 60,
       23, 81, 59, 45, 16, 16, 96, 78, 82, 58, 47, 20, 46])

In [212]:
a

array([[80, 18, 88, 12, 31, 27],
       [ 9, 52, 62, 85, 53, 75],
       [26, 10, 32, 40, 60, 23],
       [81, 59, 45, 16, 16, 96],
       [78, 82, 58, 47, 20, 46]])

In [213]:
c.resize((3, 10))

In [214]:
c

array([[80, 18, 88, 12, 31, 27,  9, 52, 62, 85],
       [53, 75, 26, 10, 32, 40, 60, 23, 81, 59],
       [45, 16, 16, 96, 78, 82, 58, 47, 20, 46]])

In [215]:
a

array([[80, 18, 88, 12, 31, 27],
       [ 9, 52, 62, 85, 53, 75],
       [26, 10, 32, 40, 60, 23],
       [81, 59, 45, 16, 16, 96],
       [78, 82, 58, 47, 20, 46]])

In [217]:
b[0, 0] = 1

In [218]:
b

array([[ 1, 18, 88, 12, 31, 27,  9, 52, 62, 85],
       [53, 75, 26, 10, 32, 40, 60, 23, 81, 59],
       [45, 16, 16, 96, 78, 82, 58, 47, 20, 46]])

In [219]:
a

array([[ 1, 18, 88, 12, 31, 27],
       [ 9, 52, 62, 85, 53, 75],
       [26, 10, 32, 40, 60, 23],
       [81, 59, 45, 16, 16, 96],
       [78, 82, 58, 47, 20, 46]])

In [221]:
c[0, 0] = 12

In [222]:
c

array([[12, 18, 88, 12, 31, 27,  9, 52, 62, 85],
       [53, 75, 26, 10, 32, 40, 60, 23, 81, 59],
       [45, 16, 16, 96, 78, 82, 58, 47, 20, 46]])

In [223]:
a

array([[ 1, 18, 88, 12, 31, 27],
       [ 9, 52, 62, 85, 53, 75],
       [26, 10, 32, 40, 60, 23],
       [81, 59, 45, 16, 16, 96],
       [78, 82, 58, 47, 20, 46]])

#### Array flattening
* np.ravel - return the quotation of the array, if you modify the value in the new array, the original array is affected.
* np.flatten - return the copy of the array, if you modify the value in the new array, the original one is not affected.

#### Array concatenation
* np.hstack - horizontal concatentation, equal to np.concatenate((x, y), axis=1)
* np.vstack - vertical concatentation, equal to np.concatenate((x, y), axis=0)

#### Aray split
* np.hsplit - horizontal split, equal to np.split(x, num, axis=1)
* np.vsplit - vertical concatentation, equal to np.split(x, num, axis=0)

In [270]:
np.vsplit?

In [259]:
x = np.random.randint(1, 50, 25).reshape((5, 5))
y = np.random.randint(1, 50, 30).reshape((5, 6))
display(x)
display(y)

array([[45,  3, 35, 35, 21],
       [21, 46, 34, 33,  2],
       [ 7, 27, 15, 18, 27],
       [33, 32, 26,  6, 39],
       [42, 13, 16, 49, 39]])

array([[16, 18, 39, 44, 37, 46],
       [29, 18, 17, 39, 10, 39],
       [46, 46, 35, 27,  4,  6],
       [ 7, 27, 19, 12, 31, 30],
       [43, 34, 31, 30, 30, 48]])

In [260]:
np.hstack((x, y))

array([[45,  3, 35, 35, 21, 16, 18, 39, 44, 37, 46],
       [21, 46, 34, 33,  2, 29, 18, 17, 39, 10, 39],
       [ 7, 27, 15, 18, 27, 46, 46, 35, 27,  4,  6],
       [33, 32, 26,  6, 39,  7, 27, 19, 12, 31, 30],
       [42, 13, 16, 49, 39, 43, 34, 31, 30, 30, 48]])

In [261]:
np.concatenate((x, y), axis=1)

array([[45,  3, 35, 35, 21, 16, 18, 39, 44, 37, 46],
       [21, 46, 34, 33,  2, 29, 18, 17, 39, 10, 39],
       [ 7, 27, 15, 18, 27, 46, 46, 35, 27,  4,  6],
       [33, 32, 26,  6, 39,  7, 27, 19, 12, 31, 30],
       [42, 13, 16, 49, 39, 43, 34, 31, 30, 30, 48]])

In [262]:
y.resize((6, 5))
y

array([[16, 18, 39, 44, 37],
       [46, 29, 18, 17, 39],
       [10, 39, 46, 46, 35],
       [27,  4,  6,  7, 27],
       [19, 12, 31, 30, 43],
       [34, 31, 30, 30, 48]])

In [263]:
np.vstack((x, y))

array([[45,  3, 35, 35, 21],
       [21, 46, 34, 33,  2],
       [ 7, 27, 15, 18, 27],
       [33, 32, 26,  6, 39],
       [42, 13, 16, 49, 39],
       [16, 18, 39, 44, 37],
       [46, 29, 18, 17, 39],
       [10, 39, 46, 46, 35],
       [27,  4,  6,  7, 27],
       [19, 12, 31, 30, 43],
       [34, 31, 30, 30, 48]])

In [264]:
np.concatenate((x, y), axis=0)

array([[45,  3, 35, 35, 21],
       [21, 46, 34, 33,  2],
       [ 7, 27, 15, 18, 27],
       [33, 32, 26,  6, 39],
       [42, 13, 16, 49, 39],
       [16, 18, 39, 44, 37],
       [46, 29, 18, 17, 39],
       [10, 39, 46, 46, 35],
       [27,  4,  6,  7, 27],
       [19, 12, 31, 30, 43],
       [34, 31, 30, 30, 48]])

In [265]:
z = y.reshape((5, 6))
z

array([[16, 18, 39, 44, 37, 46],
       [29, 18, 17, 39, 10, 39],
       [46, 46, 35, 27,  4,  6],
       [ 7, 27, 19, 12, 31, 30],
       [43, 34, 31, 30, 30, 48]])

In [266]:
np.hsplit(z, 2)

[array([[16, 18, 39],
        [29, 18, 17],
        [46, 46, 35],
        [ 7, 27, 19],
        [43, 34, 31]]),
 array([[44, 37, 46],
        [39, 10, 39],
        [27,  4,  6],
        [12, 31, 30],
        [30, 30, 48]])]

In [267]:
y1, y2 = np.vsplit(y, 2)

In [268]:
display(y1)
display(y2)

array([[16, 18, 39, 44, 37],
       [46, 29, 18, 17, 39],
       [10, 39, 46, 46, 35]])

array([[27,  4,  6,  7, 27],
       [19, 12, 31, 30, 43],
       [34, 31, 30, 30, 48]])

In [276]:
matr1 = np.mat("1 2 3;4 5 6;7 8 9")
matr2 = np.matrix([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
matr3 = np.matrix("1 2 3;4 5 6;7 8 9", copy=False)

In [277]:
display(matr1)
display(matr2)
display(matr3)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [275]:
np.mat?

In [293]:
aa = np.random.randint(1, 10, 9).reshape((3, 3))
bb = np.random.randint(1, 10, 3)
display(aa)
display(bb)

array([[3, 1, 4],
       [8, 3, 9],
       [9, 1, 4]])

array([7, 6, 1])

In [294]:
np.add(aa, bb)

array([[10,  7,  5],
       [15,  9, 10],
       [16,  7,  5]])

In [295]:
xx = np.array([1, 2, 3])
yy = np.array([[1], [2], [3]])
display(xx)
display(yy)

array([1, 2, 3])

array([[1],
       [2],
       [3]])

In [296]:
xx + yy

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [297]:
import os

os.getcwd()

'C:\\Users\\PSPX_a_JIAGAO\\Documents\\Programming\\Python\\Python_Jupyter'

In [299]:
np.savez(r".\testz.npy", aa, bb, xx, yy)

In [310]:
a

array([[ 1, 18, 88, 12, 31, 27],
       [ 9, 52, 62, 85, 53, 75],
       [26, 10, 32, 40, 60, 23],
       [81, 59, 45, 16, 16, 96],
       [78, 82, 58, 47, 20, 46]])

In [316]:
np.sort(a, axis=0)

array([[ 1, 10, 32, 12, 16, 23],
       [ 9, 18, 45, 16, 20, 27],
       [26, 52, 58, 40, 31, 46],
       [78, 59, 62, 47, 53, 75],
       [81, 82, 88, 85, 60, 96]])

In [311]:
np.sort(a, axis=1)

array([[ 1, 12, 18, 27, 31, 88],
       [ 9, 52, 53, 62, 75, 85],
       [10, 23, 26, 32, 40, 60],
       [16, 16, 45, 59, 81, 96],
       [20, 46, 47, 58, 78, 82]])

In [312]:
np.argsort(a, axis=1)

array([[0, 3, 1, 5, 4, 2],
       [0, 1, 4, 2, 5, 3],
       [1, 5, 0, 2, 3, 4],
       [3, 4, 2, 1, 0, 5],
       [4, 5, 3, 2, 0, 1]], dtype=int64)

In [317]:
np.sort(a)

array([[ 1, 12, 18, 27, 31, 88],
       [ 9, 52, 53, 62, 75, 85],
       [10, 23, 26, 32, 40, 60],
       [16, 16, 45, 59, 81, 96],
       [20, 46, 47, 58, 78, 82]])

In [321]:
aaa = [[1, 5, 1, 4, 3, 4, 4]]
bbb = [[9, 4, 0, 4, 0, 2, 1]]
np.lexsort((bbb, aaa))

array([[2, 0, 4, 6, 5, 3, 1]], dtype=int64)

In [322]:
arr1 = np.random.randint(1, 100, (5, 6))
arr2 = np.random.randint(1, 100, (5, 6))
display(arr1)
display(arr2)

array([[52, 13, 60, 26, 40, 34],
       [25,  8, 69, 82, 70, 70],
       [82, 21, 87,  2, 75, 71],
       [49, 56, 52, 98, 40,  1],
       [31, 43, 88, 72,  5, 63]])

array([[26, 18, 51, 64, 18, 74],
       [ 2, 23, 34, 28, 83, 30],
       [ 3, 63, 56, 11, 91, 54],
       [89, 55, 10, 76, 50, 17],
       [67, 74, 30, 61,  2, 78]])

In [325]:
arr1.reshape((30,))

array([52, 13, 60, 26, 40, 34, 25,  8, 69, 82, 70, 70, 82, 21, 87,  2, 75,
       71, 49, 56, 52, 98, 40,  1, 31, 43, 88, 72,  5, 63])

In [328]:
arr3 = arr1.ravel()
arr4 = arr2.flatten()

In [329]:
display(arr3)
display(arr4)

array([52, 13, 60, 26, 40, 34, 25,  8, 69, 82, 70, 70, 82, 21, 87,  2, 75,
       71, 49, 56, 52, 98, 40,  1, 31, 43, 88, 72,  5, 63])

array([26, 18, 51, 64, 18, 74,  2, 23, 34, 28, 83, 30,  3, 63, 56, 11, 91,
       54, 89, 55, 10, 76, 50, 17, 67, 74, 30, 61,  2, 78])

In [331]:
arr3[0] = 1
arr4[0] = 1
display(arr1)
display(arr2)

array([[ 1, 13, 60, 26, 40, 34],
       [25,  8, 69, 82, 70, 70],
       [82, 21, 87,  2, 75, 71],
       [49, 56, 52, 98, 40,  1],
       [31, 43, 88, 72,  5, 63]])

array([[26, 18, 51, 64, 18, 74],
       [ 2, 23, 34, 28, 83, 30],
       [ 3, 63, 56, 11, 91, 54],
       [89, 55, 10, 76, 50, 17],
       [67, 74, 30, 61,  2, 78]])

In [332]:
arr1.flatten(order="F")

array([ 1, 25, 82, 49, 31, 13,  8, 21, 56, 43, 60, 69, 87, 52, 88, 26, 82,
        2, 98, 72, 40, 70, 75, 40,  5, 34, 70, 71,  1, 63])

In [334]:
np.unique(arr1)

array([ 1,  2,  5,  8, 13, 21, 25, 26, 31, 34, 40, 43, 49, 52, 56, 60, 63,
       69, 70, 71, 72, 75, 82, 87, 88, 98])

In [337]:
np.tile(arr1, 3)

array([[ 1, 13, 60, 26, 40, 34,  1, 13, 60, 26, 40, 34,  1, 13, 60, 26,
        40, 34],
       [25,  8, 69, 82, 70, 70, 25,  8, 69, 82, 70, 70, 25,  8, 69, 82,
        70, 70],
       [82, 21, 87,  2, 75, 71, 82, 21, 87,  2, 75, 71, 82, 21, 87,  2,
        75, 71],
       [49, 56, 52, 98, 40,  1, 49, 56, 52, 98, 40,  1, 49, 56, 52, 98,
        40,  1],
       [31, 43, 88, 72,  5, 63, 31, 43, 88, 72,  5, 63, 31, 43, 88, 72,
         5, 63]])

In [344]:
arr1.repeat(3)

array([ 1,  1,  1, 13, 13, 13, 60, 60, 60, 26, 26, 26, 40, 40, 40, 34, 34,
       34, 25, 25, 25,  8,  8,  8, 69, 69, 69, 82, 82, 82, 70, 70, 70, 70,
       70, 70, 82, 82, 82, 21, 21, 21, 87, 87, 87,  2,  2,  2, 75, 75, 75,
       71, 71, 71, 49, 49, 49, 56, 56, 56, 52, 52, 52, 98, 98, 98, 40, 40,
       40,  1,  1,  1, 31, 31, 31, 43, 43, 43, 88, 88, 88, 72, 72, 72,  5,
        5,  5, 63, 63, 63])

In [346]:
arr1.repeat(3, axis=0)

array([[ 1, 13, 60, 26, 40, 34],
       [ 1, 13, 60, 26, 40, 34],
       [ 1, 13, 60, 26, 40, 34],
       [25,  8, 69, 82, 70, 70],
       [25,  8, 69, 82, 70, 70],
       [25,  8, 69, 82, 70, 70],
       [82, 21, 87,  2, 75, 71],
       [82, 21, 87,  2, 75, 71],
       [82, 21, 87,  2, 75, 71],
       [49, 56, 52, 98, 40,  1],
       [49, 56, 52, 98, 40,  1],
       [49, 56, 52, 98, 40,  1],
       [31, 43, 88, 72,  5, 63],
       [31, 43, 88, 72,  5, 63],
       [31, 43, 88, 72,  5, 63]])

In [348]:
np.mean(arr1)

47.8

In [350]:
np.mean(arr1, axis=1)

array([29.        , 54.        , 56.33333333, 49.33333333, 50.33333333])

In [351]:
np.mean(arr1, axis=0)

array([37.6, 28.2, 71.2, 56. , 46. , 47.8])

In [352]:
xxx = np.array([1, 2, 3])
yyy = np.array([4, 5, 6])

In [353]:
np.hstack((xxx, yyy))

array([1, 2, 3, 4, 5, 6])

In [356]:
np.ones((3, 3)) + np.ones((3, ))

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])